import streamlit as st
from firebase_admin import firestore, initialize_app, credentials
from langchain import PromptTemplate, LLMChain
from langchain_community.chat_models import ChatOpenAI
from llama_index import SimpleVectorIndex as VectorStoreIndex, Document
from config import OPENAI_API_KEY

# Initialize Firebase if not already initialized
try:
    db = firestore.client()
except ValueError:
    # Replace 'path/to/serviceAccountKey.json' with your actual path
    cred = credentials.Certificate("path/to/serviceAccountKey.json")
    initialize_app(cred)
    db = firestore.client()

# Initialize OpenAI LLM
llm = ChatOpenAI(temperature=0.7, model="gpt-4", openai_api_key=OPENAI_API_KEY)


def create_resume_index(resume_data):
    """
    Creates a vector index from the user's resume data using LlamaIndex.

    Args:
        resume_data (dict): Parsed resume data containing 'experience' and 'skills'.

    Returns:
        VectorStoreIndex: An index built from the resume documents.
    """
    documents = [Document(text=resume_data.get('experience', ''))]
    skills = resume_data.get('skills', [])
    for skill in skills:
        documents.append(Document(text=skill))
    return VectorStoreIndex.from_documents(documents)


def generate_resume(resume_data, job_description):
    """
    Generates a tailored resume based on the user's resume data and the job description.

    Args:
        resume_data (dict): Parsed resume data.
        job_description (str): The job description for which the resume is tailored.

    Returns:
        str: The tailored resume generated by the AI.
    """
    resume_index = create_resume_index(resume_data)

    # Retrieve relevant information from the resume using LlamaIndex
    query = "Identify the most relevant experiences and skills for the following job:"
    relevant_info = resume_index.query(f"{query}\n\n{job_description}")

    resume_template = """
    Given the following relevant resume information and job description, create a tailored resume:

    Relevant Resume Information:
    {relevant_info}

    Job Description:
    {job_description}

    Tailored Resume:
    """

    resume_prompt = PromptTemplate(
        input_variables=["relevant_info", "job_description"],
        template=resume_template)

    resume_chain = LLMChain(llm=llm, prompt=resume_prompt)

    tailored_resume = resume_chain.run(relevant_info=relevant_info.response,
                                       job_description=job_description)
    return tailored_resume


def generate_cover_letter(resume_data, job_description):
    """
    Generates a compelling cover letter based on the user's resume data and the job description.

    Args:
        resume_data (dict): Parsed resume data.
        job_description (str): The job description for which the cover letter is tailored.

    Returns:
        str: The generated cover letter.
    """
    resume_index = create_resume_index(resume_data)

    # Retrieve relevant information from the resume using LlamaIndex
    query = "Identify key qualifications and experiences relevant to the following job:"
    relevant_info = resume_index.query(f"{query}\n\n{job_description}")

    cover_letter_template = """
    Write a compelling cover letter for the following job based on the given relevant resume information:

    Relevant Resume Information:
    {relevant_info}

    Job Description:
    {job_description}

    Cover Letter:
    """

    cover_letter_prompt = PromptTemplate(
        input_variables=["relevant_info", "job_description"],
        template=cover_letter_template)

    cover_letter_chain = LLMChain(llm=llm, prompt=cover_letter_prompt)

    cover_letter = cover_letter_chain.run(relevant_info=relevant_info.response,
                                          job_description=job_description)
    return cover_letter


def generate_documents():
    """
    Streamlit interface for generating and saving tailored resume and cover letter.
    """
    st.subheader("Generate Tailored Resume and Cover Letter")

    user_id = st.session_state.get('user', {}).get('uid')
    if not user_id:
        st.warning("User not authenticated!")
        return

    user_doc = db.collection('users').document(user_id).get()

    if not user_doc.exists or 'resume_data' not in user_doc.to_dict():
        st.warning("Please upload your resume first!")
        return

    resume_data = user_doc.to_dict().get('resume_data', {})

    job_description = st.text_area("Paste the job description here:")

    if st.button("Generate Documents"):
        if not job_description.strip():
            st.warning("Please provide a job description.")
            return

        with st.spinner("Generating tailored resume and cover letter..."):
            tailored_resume = generate_resume(resume_data, job_description)
            cover_letter = generate_cover_letter(resume_data, job_description)

        st.subheader("Tailored Resume")
        st.text_area("", tailored_resume, height=300)

        st.subheader("Cover Letter")
        st.text_area("", cover_letter, height=300)

        if st.button("Save Generated Documents"):
            db.collection('users').document(user_id).set(
                {
                    'generated_documents': {
                        'resume': tailored_resume,
                        'cover_letter': cover_letter
                    }
                },
                merge=True)
            st.success("Documents saved successfully!")
